name: Hello Username
inputs:
  my-username:
    description: Please enter your username
    required: true
    default: "ShubhamPalriwala"
  GITHUB_TOKEN:
    required: true
outputs:
  time:
    description: "Time we greeted you"

runs:
  using: "node12"
  main: "index.js"
